// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx echo.Context) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx echo.Context) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx echo.Context) error
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(ctx echo.Context) error
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(ctx echo.Context, params GetTeamGetParams) error
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(ctx echo.Context, params GetUsersGetReviewParams) error
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostPullRequestCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestCreate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestCreate(ctx)
	return err
}

// PostPullRequestMerge converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestMerge(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestMerge(ctx)
	return err
}

// PostPullRequestReassign converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestReassign(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestReassign(ctx)
	return err
}

// PostTeamAdd converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeamAdd(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeamAdd(ctx)
	return err
}

// GetTeamGet converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeamGet(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams
	// ------------- Required query parameter "team_name" -------------

	err = runtime.BindQueryParameter("form", true, true, "team_name", ctx.QueryParams(), &params.TeamName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter team_name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeamGet(ctx, params)
	return err
}

// GetUsersGetReview converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersGetReview(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersGetReview(ctx, params)
	return err
}

// PostUsersSetIsActive converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSetIsActive(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSetIsActive(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(baseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(baseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.POST(baseURL+"/team/add", wrapper.PostTeamAdd)
	router.GET(baseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(baseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(baseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xabW8bxxH+K4ttgTgALVK0XaD8xtiKqg+WWYoGigqCsOKtpEvuzXd7agSDgF7Suq2M",
	"qvlWBEiMwH+ApsWK1gv1F2b/UTG7R94deTxRpiwX+WJTx73d2dlnnnlmli9p07U91+GOCGjlJfWYz2wu",
	"uK/+anBmLzOb/zHk/i4+MHjQ9E1PmK5DKxTewiX04AzacC5fwyX0oUugBxfymMAZ9OEC2nAJJ/KIFqiJ",
	"b7xQExWow2xOK1RwZq+rzwXq8xeh6XODVoQf8gINmtvcZrio2PVwcCB809mirVaBPg+4v2RMsuo/cAJd",
	"uJQH0JPfa/vkAfTlHoEr6CtTT6EPHfW4C+fyeIJ5YcD9ddO4kXGtwZfKgQu+7/p1HniuE3B8wL9jtmfp",
	"j/gdfmi6Bk6x/Kyx/vWz58tPaIHaPAjYFj71eeCGfpMTxxVk0w0dQ3nA812P+8LkQWqq9GM98UvKndCm",
	"lVXaWKg+XV/409JKY4UWaK2e+vx0ob64gGujHdWVlaXF5ejP9cfV5SdLT6qNhehbbeVaYXTzCbuzTi12",
	"4qo2LR4fz+VufMObYmy83uH4sAKthZZV5y9CHohxD7AgMLccbqz7fMfkf4lgncZLdMoELqENp/ivfIX4",
	"gUt5JP9K5B50oSNfy39BB7pyD5FD7pXm5spfImwEt4OM7Q4NZb7PdvFvFoptV8Epa3TT50xwo6r2sOn6",
	"NhO0Qg0m+H1hqvhwQstiGwgdDcEM3/tbs83ghZa17mtfTjI0NUbHScaoQDARBknsPastLNMCjVA2jp2R",
	"8x41JWvhpE+HSxayzvwa3Kxsu34WeHJP7NfgrCy/IOeP+8Lm9kYUPUPI/9bnm7RCf1OMU0gx4r4izvJU",
	"vZMVCzHvX0sUyRQxMGKS2dGCY8abwTprCnMnudyG61qcOfjqgOazzga/m87QOFkM3ykkVs6yGdPYja3N",
	"890n3UvyJPL2hZOZzqarljEF8g2t1Uk9ikZSVfFpc0eQFe7vmE1O7jV4IEiDBd8WyNfMski5VH6E9LrD",
	"/UCz9Pxcaa6Eu3A97jDPpBX6YK409wDBzsS28lzRi2O6qBlVudfVqQGdzJD0lww0yQ1EggMe6+HaDzwQ",
	"X7nGrs6hjuCOep95nmU21QzFbwK0KpXPE3RBw3mawRDU8+/Pl0rzmQFaoVXDIAFnfnObtpIS43Ow0owM",
	"k42KtIpSD7QyUhsrl+Zv5nDPn5TiV2lYRvA+QENu81xistYc3co5KG1eHkkmpUurlemytFSp1Ynchz6c",
	"wgkqazzMh6WHU3gttjHPnrRazVgf/g0dLaWLSX0PbRRPXa2gPkTq+0hb9/ubnemoKE6K1FgU1+rENAiz",
	"fM6MXcK/MwMRjJzFTPtEPx/Cf6FL5L48lP+ArtyXB9CRh9CVB3ql0LYZlh8UfhmciDyQr0mtTqBHoK09",
	"hS5ShcgrnAPO8Kukzuypd+AE+qScLTWhB6cj1dRwdrkHbWRmtqVAn8BTQNfQyhQjKoE4NSE+VaNn4MPJ",
	"YZYXNNfy1zXM9HHMU7ob5oklOsUMd3++dL/8sDFfrjx4WHn0uz/fGjdFwvHu2Qk6iqBUtPTlsWoP9MjA",
	"nDtmK7RnlJZGY/eNiquuCtFB9J5BG84io8k96Kk3L+AK+qpfcCkPVPAeE+jDlYrTtvwb9OTxl9PHos81",
	"eqYOx/rghRki0rVirEaoLOdiLgc/OFee2Jw5kAupJT5/WKPSDB99ckGBe/As1uTG+gYiNHxEby+KRybP",
	"6YT0oQN9eA/98aSkMk7+Ufo0vdLaFOwBb9Ts3bE2TA9DuCOPdPMOIxrt+yxs0oNzTODZXcTXWWxzQwkU",
	"1dqYJZTpMVH9pNeAU+SdC0VDx1o7IC/twzl0ybCFt8OscJKcGg6K5VSTOY4ryICTiOsQbQOp1bUrHPcx",
	"cwzTiCqqtF3yQAkYJH15CFdR30zRKIrDnpZG6Ks800b6jLF1jkt0rUkiSKnSsTmwh5gOwdJ0YKioRvE7",
	"Yuib3EN7J4/gfKwFmKXILvI3keqdJtu4UfVrBqqTOyAZIlwits0g8vTtSVj4CdpyTx7Kv8dBdKKT3bC1",
	"CVcYztBBXJMolWXEnzwez5rjQyMli0L1Es7wa5UnJ5GI8jWBE7QRh6hhWut29efRC4SczIrnX2SGkZ9N",
	"G5zZVcOYJYMO22CrqT6N7qcO06HOCnG7hVYts8lpq5D/Ujn90lfuBm2tpRo+1GO7trqqmRoojWFo3HL1",
	"LaI+4ed2yQZrfsujW5FJaXJg6xSOmiZT/ZgqfZMVObQ15Zdmq3rTFzUxiwz3/Qlr39HdfWwdnIrfQyL3",
	"iTyUr6CtZhhcG15Aj9yLHSh/kAdF6MO7SIGcy2OdXjIzLnThQ1Jy4wmmGGGLK+dH/6UJYZErPljkQnUQ",
	"41vP1Wz/xUOK6VtRxONssvP/JoJuzikj0PkZ3sl/QhfO8MzS/H3nraof8/tTGKnjpeC5wmjvRgCegEB0",
	"eoAQ1I3vPCA+x6GLw5E3xWPyNnx2NCYLFr38J6131kbQOmVvaPqbqLF7voz7qMmF7MSLkbQxUxU4v8AV",
	"9BTZnZFa/Qvd3Zv0i4RrwFmrfyGPCgTeI5pzK5KpBO0AwAqJKQAHXCwF1eF91GR1pV5dSYyeQWYlCG2T",
	"WQGfHiMffdU38aCvu+q65R5EGN0Jjrsgi7KvpfocVw1WygsedUM5nSj6OZG1f9AlBnyYiMy7zwdvpi/a",
	"06H3VhF+O9qcDj/5PZxDG94TaGOygx508Hs1spf3M6OxQGsNn70c/OxIZxFM7NEDPTjxIFUCJZ7/gTNL",
	"bNPWWut/AQAA//80B9xs2CUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
